"""empty message

Revision ID: 783ab51ec69f
Revises: 47ff57773455
Create Date: 2019-08-14 12:50:37.821492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783ab51ec69f'
down_revision = '47ff57773455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'message',
               existing_type=sa.VARCHAR(length=100),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'message',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
