"""empty message

Revision ID: a32afdf9747d
Revises: a8bd1aaccb3a
Create Date: 2019-08-12 12:16:06.246286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a32afdf9747d'
down_revision = 'a8bd1aaccb3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('lookupId', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('notes', sa.Column('numViews', sa.Integer(), nullable=True))
    op.alter_column('notes', 'message',
               existing_type=sa.VARCHAR(length=100),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'message',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('notes', 'numViews')
    op.drop_column('notes', 'lookupId')
    # ### end Alembic commands ###
